# jdbc:mysql://209.209.40.85:19783/master_db
# admin
# gqa6vDtX
master:
  datasource:
    url: jdbc:mysql://localhost:3306/master_db
    username: root
    password: mustafa123@

provisioning:
  datasource:
    host: 108.181.197.152
    username: root
    password: mustafa123@
    port: "3306"

spring:
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    show-sql: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.example.com
    port: 587
    username: your-email@example.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  company:
    default-email: sales@yourcompany.com

server:
  port: 8080 # Default HTTP port
  # ssl:
  #   enabled: false # Disabled for local development
  #   key-store-type: PKCS12
  #   key-store: classpath:keystore.p12
  #   key-store-password: password
  #   key-alias: myapp
# jdbc:mysql://209.209.40.85:19783/master_db
# admin
# gqa6vDtX

# master:
#   datasource:
#     url: jdbc:mysql://108.181.197.152:16319/master_db
#     username: admin
#     password: AUTODoxj

# provisioning:
#   datasource:
#     host: 108.181.197.152
#     username: admin
#     password: AUTODoxj
#     port: 16319



# master:
#   datasource:
#     url: jdbc:mysql://localhost:3306/master_db
#     username: root
#     password: mustafa123@

# provisioning:
#   datasource:
#     host: 108.181.197.152
#     username: root
#     password: mustafa123@
#     port: "3306"


# master:
#   datasource:
#     url: jdbc:mysql://108.181.197.152:16319/master_db
#     username: admin
#     password: AUTODoxj

# provisioning:
#   datasource:
#     host: 108.181.197.152
#     username: admin
#     password: AUTODoxj
#     port: 16319